apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mariadb
  namespace: wordpress
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: mariadb
    spec:
      containers:
      - image: mariadb:10.5.5
        name: mariadb
        envFrom:
          - configMapRef:
              name: wp-configmap
          - secretRef:
              name: mariadb-pass
        ports:
        - containerPort: 3306
          protocol: TCP
          name: mariadb
        volumeMounts:
        - name: db-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: db-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
