apiVersion: v1
kind: Secret
metadata:
  name: mariadb-pass
  namespace: wordpress
type: Opaque
data:
  MYSQL_USER: <USERNAME>
  MYSQL_PASSWORD: <PASSWORD>
  MYSQL_ROOT_PASSWORD: <ROOT PASSWORD>
